spring.application.name=tool-calling-demo
server.port=8181
spring.ai.openai.api-key=${OPENAI_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

app.weather.api-key=70eda467c1494dd992a151714250406